export enum Paths {
  Main = '/',
  SignIn = '/sign_in',
  Portal = '/portal',
  Dashboard = 'dashboard',
  Documents = 'documents',
  Maintenance = 'maintenance',
  NewMaintenance = 'maintenance/new',
  ServiceCharges = 'service-charges',
  Community = 'community',
  Messages = 'messages',
  Market = 'market',
  Events = 'events',
  Subletting = 'subletting',
  Profile = 'profile',
  Notifications = 'notifications',
}
